version: '3.8'

services:
  # Test Database
  postgres-test:
    image: postgres:16-alpine
    container_name: querodocumento-db-test
    environment:
      - POSTGRES_USER=querodoc_test
      - POSTGRES_PASSWORD=test123
      - POSTGRES_DB=querodocumento_test
    ports:
      - "5434:5432"
    networks:
      - test-network
    # Optimized for speed in testing
    command: >
      postgres
        -c fsync=off
        -c synchronous_commit=off
        -c full_page_writes=off
        -c checkpoint_segments=32
        -c checkpoint_completion_target=0.9
        -c wal_buffers=16MB
        -c shared_buffers=256MB

  # Test Redis
  redis-test:
    image: redis:7-alpine
    container_name: querodocumento-redis-test
    command: redis-server --save "" --appendonly no
    ports:
      - "6381:6379"
    networks:
      - test-network

  # MailHog for email testing
  mailhog-test:
    image: mailhog/mailhog:latest
    container_name: querodocumento-mailhog-test
    ports:
      - "1026:1025"  # SMTP
      - "8026:8025"  # Web UI
    networks:
      - test-network

volumes: {}

networks:
  test-network:
    driver: bridge